// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using generator_web.Models;

#nullable disable

namespace generator_web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251001154828_float_data")]
    partial class float_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("generator_web.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("generator_web.Models.ControlAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsExecuted")
                        .HasColumnType("bit");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ControlActions");
                });

            modelBuilder.Entity("generator_web.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("generator_web.Models.generator_data", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("BataryaVoltaji")
                        .HasColumnType("real");

                    b.Property<string>("CalismaDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GenGucFaktoru")
                        .HasColumnType("real");

                    b.Property<float>("GenHz")
                        .HasColumnType("real");

                    b.Property<float>("GenUretilenGuc")
                        .HasColumnType("real");

                    b.Property<float>("GenVoltaj_l1")
                        .HasColumnType("real");

                    b.Property<float>("GenVoltaj_l2")
                        .HasColumnType("real");

                    b.Property<float>("GenVoltaj_l3")
                        .HasColumnType("real");

                    b.Property<bool>("KapatmaAlarmi")
                        .HasColumnType("bit");

                    b.Property<float>("MotorRpm")
                        .HasColumnType("real");

                    b.Property<float>("MotorSicaklik")
                        .HasColumnType("real");

                    b.Property<int>("OperationMode")
                        .HasColumnType("int");

                    b.Property<bool>("SebekeDurumu")
                        .HasColumnType("bit");

                    b.Property<float>("SebekeHz")
                        .HasColumnType("real");

                    b.Property<float>("SebekeVoltaj_l1")
                        .HasColumnType("real");

                    b.Property<float>("SebekeVoltaj_l2")
                        .HasColumnType("real");

                    b.Property<float>("SebekeVoltaj_l3")
                        .HasColumnType("real");

                    b.Property<long>("SistemCalismaSuresi")
                        .HasColumnType("bigint");

                    b.Property<bool>("SistemSaglikli")
                        .HasColumnType("bit");

                    b.Property<float>("ToplamGuc")
                        .HasColumnType("real");

                    b.Property<bool>("UyariAlarmi")
                        .HasColumnType("bit");

                    b.Property<float>("YagBasinci")
                        .HasColumnType("real");

                    b.Property<float>("YakitSeviyesi")
                        .HasColumnType("real");

                    b.Property<bool>("YukAtmaAlarmi")
                        .HasColumnType("bit");

                    b.Property<long>("timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("generator_datas");
                });
#pragma warning restore 612, 618
        }
    }
}
